version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017
    depends_on:
      - mongodb
