version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_cluster
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      # - "1883:1883" #unsecured mqtt port
      - "8883:8883" #secured mqtt port
      - "9001:9001" #mqtt port for websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
