version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
