version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - SECRET_REFRESH_KEY=${SECRET_REFRESH_KEY}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      # - NODE_ENV=production
    depends_on:
      - mongodb
      - mqtt
